Add Submit button while previewing a new post
NEAR-DevHub/neardevhub-bos pull request #601
Opened 2023-12-24 13:58 UTC by itexpert120

Fixes https://github.com/NEAR-DevHub/neardevhub-bos/issues/596

2023-12-26 12:40 UTC, Tguntenaar commented
@itexpert120 could you please share a preview link of the UI changes you've made with every PR? This will speed up the review process.

2023-12-26 12:41 UTC, Tguntenaar requested changes
@itexpert120 could you please share a preview link of the UI changes you've made with every PR? This will speed up the review process.

2023-12-27 21:40 UTC, itexpert120 commented
@Tguntenaar Added preview

2023-12-27 21:56 UTC, elliotBraem approved these changes

2023-12-29 16:47 UTC, Tguntenaar approved these changes

2023-12-29 16:47 UTC, merged